In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
raw_dir = os.getcwd()

In [3]:
filename = os.path.join(raw_dir, 'dataset', 'olist_products_dataset.csv')

In [4]:
df = pd.read_csv(filename)

In [5]:
df

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0
...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

In [6]:
df = df.drop(['product_name_lenght', 'product_description_lenght', 'product_photos_qty'], axis=1)

In [7]:
df.describe()

,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32949.000000,32949.000000,32949.000000,32949.000000
mean,2276.472488,30.815078,16.937661,23.196728
std,4282.038731,16.914458,13.637554,12.079047
min,0.000000,7.000000,2.000000,6.000000
25%,300.000000,18.000000,8.000000,15.000000
50%,700.000000,25.000000,13.000000,20.000000
75%,1900.000000,38.000000,21.000000,30.000000
max,40425.000000,105.000000,105.000000,118.000000

In [8]:
check_nan = df.isnull().values.any()

In [9]:
check_nan

True

In [10]:
check_nan = df.isnull().sum().sum()
check_nan

618

In [11]:
df = df.dropna(subset=['product_category_name'])
df

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,625.0,20.0,17.0,13.0
...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,2083.0,12.0,2.0,7.0

In [12]:
check_nan = df.isnull().sum().sum()
check_nan

4

In [13]:
df[df.isnull().any(axis=1)]

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm
8578,09ff539a621711667c43eba6a3bd8466,bebes,NaN,NaN,NaN,NaN

In [14]:
df = df.dropna()
df

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,625.0,20.0,17.0,13.0
...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,2083.0,12.0,2.0,7.0

In [15]:
check_nan = df.isnull().sum().sum()
check_nan

0

In [16]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [product_id, product_category_name, product_weight_g, product_length_cm, product_height_cm, product_width_cm]
Index: []

In [17]:
df.reset_index(drop=True, inplace=True)
df

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,625.0,20.0,17.0,13.0
...,...,...,...,...,...,...
32335,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,12300.0,40.0,40.0,40.0
32336,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,1700.0,16.0,19.0,16.0
32337,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,1400.0,27.0,7.0,27.0
32338,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,700.0,31.0,13.0,20.0
32339,106392145fca363410d287a815be6de4,cama_mesa_banho,2083.0,12.0,2.0,7.0

In [18]:
filename1 = os.path.join(raw_dir, 'dataset', 'product_category_name_translation.csv')

In [19]:
df_name = pd.read_csv(filename1)
df_name

            product_category_name product_category_name_english
0                    beleza_saude                 health_beauty
1          informatica_acessorios         computers_accessories
2                      automotivo                          auto
3                 cama_mesa_banho                bed_bath_table
4                moveis_decoracao               furniture_decor
..                            ...                           ...
66                         flores                       flowers
67             artes_e_artesanato         arts_and_craftmanship
68                fraldas_higiene           diapers_and_hygiene
69  fashion_roupa_infanto_juvenil     fashion_childrens_clothes
70             seguros_e_servicos         security_and_services

[71 rows x 2 columns]

In [20]:
df_merged = df.merge(df_name, on='product_category_name', how='left')
df_merged

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,225.0,16.0,10.0,14.0,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,1000.0,30.0,18.0,20.0,art
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,154.0,18.0,9.0,15.0,sports_leisure
3,cef67bcfe19066a932b7673e239eb23d,bebes,371.0,26.0,4.0,26.0,baby
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,625.0,20.0,17.0,13.0,housewares
...,...,...,...,...,...,...,...
32335,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,12300.0,40.0,40.0,40.0,furniture_decor
32336,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,1700.0,16.0,19.0,16.0,construction_tools_lights
32337,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,1400.0,27.0,7.0,27.0,bed_bath_table
32338,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,700.0,31.0,13.0,20.0,computers_accessories
32339,106392145fca363410d287a815be6de4,cama_mesa_banho,2083.0,12.0,2.0,7.0,bed_bath_table

In [21]:
df_merged[df_merged.isnull().any(axis=1)]

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english
1581,0105b5323d24fc655f73052694dbbb3a,pc_gamer,2839.0,19.0,16.0,18.0,NaN
5703,6fd83eb3e0799b775e4f946bd66657c0,portateis_cozinha_e_preparadores_de_alimentos,1200.0,25.0,33.0,25.0,NaN
7176,5d923ead886c44b86845f69e50520c3e,portateis_cozinha_e_preparadores_de_alimentos,1200.0,25.0,33.0,25.0,NaN
7326,6727051471a0fc4a0e7737b57bff2549,pc_gamer,650.0,16.0,22.0,20.0,NaN
8647,bed164d9d628cf0593003389c535c6e0,portateis_cozinha_e_preparadores_de_alimentos,850.0,30.0,21.0,22.0,NaN
10822,1220978a08a6b29a202bc015b18250e9,portateis_cozinha_e_preparadores_de_alimentos,1200.0,25.0,33.0,25.0,NaN
13995,ae62bb0f95af63d64eae5f93dddea8d3,portateis_cozinha_e_preparadores_de_alimentos,10600.0,40.0,20.0,38.0,NaN
15874,1954739d84629e7323a4295812a3e0ec,portateis_cozinha_e_preparadores_de_alimentos,750.0,30.0,30.0,30.0,NaN
16608,dbe520fb381ad695a7e1f2807d20c765,pc_gamer,800.0,18.0,22.0,22.0,NaN
17459,c7a3f1a7f9eef146cc499368b578b884,portateis_cozinha_e_preparadores_de_alimentos,7350.0,40.0,30.0,23.0,NaN
18251,7afdd65f79f63819ff5bee328843fa37,portateis_cozinha_e_preparadores_de_alimentos,750.0,20.0,20.0,20.0,NaN
26397,a4756663d007b0cd1af865754d08d968,portateis_cozinha_e_preparadores_de_alimentos,650.0,22.0,6.0,14.0,NaN
29369,cb9d764f38ee4d0c00af64d5c388f837,portateis_cozinha_e_preparadores_de_alimentos,625.0,28.0,27.0,24.0,NaN

In [22]:
df_merged.loc[df_merged['product_category_name']=='pc_gamer', 'product_category_name_english'] = 'pc_gamer'

In [23]:
df_merged[df_merged['product_category_name_english']=='pc_gamer']

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english
1581,0105b5323d24fc655f73052694dbbb3a,pc_gamer,2839.0,19.0,16.0,18.0,pc_gamer
7326,6727051471a0fc4a0e7737b57bff2549,pc_gamer,650.0,16.0,22.0,20.0,pc_gamer
16608,dbe520fb381ad695a7e1f2807d20c765,pc_gamer,800.0,18.0,22.0,22.0,pc_gamer

In [24]:
df_merged.fillna(value='portable_kitchen_and_food_preparators', inplace=True)

In [25]:
df_merged[df_merged.isnull().any(axis=1)]

Empty DataFrame
Columns: [product_id, product_category_name, product_weight_g, product_length_cm, product_height_cm, product_width_cm, product_category_name_english]
Index: []

In [26]:
df_merged[df_merged['product_category_name_english']=='portable_kitchen_and_food_preparators']

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english
5703,6fd83eb3e0799b775e4f946bd66657c0,portateis_cozinha_e_preparadores_de_alimentos,1200.0,25.0,33.0,25.0,portable_kitchen_and_food_preparators
7176,5d923ead886c44b86845f69e50520c3e,portateis_cozinha_e_preparadores_de_alimentos,1200.0,25.0,33.0,25.0,portable_kitchen_and_food_preparators
8647,bed164d9d628cf0593003389c535c6e0,portateis_cozinha_e_preparadores_de_alimentos,850.0,30.0,21.0,22.0,portable_kitchen_and_food_preparators
10822,1220978a08a6b29a202bc015b18250e9,portateis_cozinha_e_preparadores_de_alimentos,1200.0,25.0,33.0,25.0,portable_kitchen_and_food_preparators
13995,ae62bb0f95af63d64eae5f93dddea8d3,portateis_cozinha_e_preparadores_de_alimentos,10600.0,40.0,20.0,38.0,portable_kitchen_and_food_preparators
15874,1954739d84629e7323a4295812a3e0ec,portateis_cozinha_e_preparadores_de_alimentos,750.0,30.0,30.0,30.0,portable_kitchen_and_food_preparators
17459,c7a3f1a7f9eef146cc499368b578b884,portateis_cozinha_e_preparadores_de_alimentos,7350.0,40.0,30.0,23.0,portable_kitchen_and_food_preparators
18251,7afdd65f79f63819ff5bee328843fa37,portateis_cozinha_e_preparadores_de_alimentos,750.0,20.0,20.0,20.0,portable_kitchen_and_food_preparators
26397,a4756663d007b0cd1af865754d08d968,portateis_cozinha_e_preparadores_de_alimentos,650.0,22.0,6.0,14.0,portable_kitchen_and_food_preparators
29369,cb9d764f38ee4d0c00af64d5c388f837,portateis_cozinha_e_preparadores_de_alimentos,625.0,28.0,27.0,24.0,portable_kitchen_and_food_preparators

In [27]:
df_merged['product_category_name'] = df_merged['product_category_name_english']
df_merged

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumery,225.0,16.0,10.0,14.0,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,art,1000.0,30.0,18.0,20.0,art
2,96bd76ec8810374ed1b65e291975717f,sports_leisure,154.0,18.0,9.0,15.0,sports_leisure
3,cef67bcfe19066a932b7673e239eb23d,baby,371.0,26.0,4.0,26.0,baby
4,9dc1a7de274444849c219cff195d0b71,housewares,625.0,20.0,17.0,13.0,housewares
...,...,...,...,...,...,...,...
32335,a0b7d5a992ccda646f2d34e418fff5a0,furniture_decor,12300.0,40.0,40.0,40.0,furniture_decor
32336,bf4538d88321d0fd4412a93c974510e6,construction_tools_lights,1700.0,16.0,19.0,16.0,construction_tools_lights
32337,9a7c6041fa9592d9d9ef6cfe62a71f8c,bed_bath_table,1400.0,27.0,7.0,27.0,bed_bath_table
32338,83808703fc0706a22e264b9d75f04a2e,computers_accessories,700.0,31.0,13.0,20.0,computers_accessories
32339,106392145fca363410d287a815be6de4,bed_bath_table,2083.0,12.0,2.0,7.0,bed_bath_table

In [28]:
df_merged = df_merged.drop('product_category_name_english', axis=1)
df_merged

,product_id,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumery,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,art,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,sports_leisure,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,baby,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,housewares,625.0,20.0,17.0,13.0
...,...,...,...,...,...,...
32335,a0b7d5a992ccda646f2d34e418fff5a0,furniture_decor,12300.0,40.0,40.0,40.0
32336,bf4538d88321d0fd4412a93c974510e6,construction_tools_lights,1700.0,16.0,19.0,16.0
32337,9a7c6041fa9592d9d9ef6cfe62a71f8c,bed_bath_table,1400.0,27.0,7.0,27.0
32338,83808703fc0706a22e264b9d75f04a2e,computers_accessories,700.0,31.0,13.0,20.0
32339,106392145fca363410d287a815be6de4,bed_bath_table,2083.0,12.0,2.0,7.0

In [29]:
df_merged.describe()

,product_weight_g,product_length_cm,product_height_cm,product_width_cm
count,32340.000000,32340.000000,32340.000000,32340.000000
mean,2276.956586,30.854545,16.958813,23.208596
std,4279.291845,16.955965,13.636115,12.078762
min,0.000000,7.000000,2.000000,6.000000
25%,300.000000,18.000000,8.000000,15.000000
50%,700.000000,25.000000,13.000000,20.000000
75%,1900.000000,38.000000,21.000000,30.000000
max,40425.000000,105.000000,105.000000,118.000000

In [30]:
duplicatedRows = df_merged[df_merged.duplicated('product_id')]

In [31]:
print(duplicatedRows)

Empty DataFrame
Columns: [product_id, product_category_name, product_weight_g, product_length_cm, product_height_cm, product_width_cm]
Index: []

In [32]:
df_merged.set_index('product_id', inplace=True)
df_merged

,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm
product_id,,,,,
1e9e8ef04dbcff4541ed26657ea517e5,perfumery,225.0,16.0,10.0,14.0
3aa071139cb16b67ca9e5dea641aaa2f,art,1000.0,30.0,18.0,20.0
96bd76ec8810374ed1b65e291975717f,sports_leisure,154.0,18.0,9.0,15.0
cef67bcfe19066a932b7673e239eb23d,baby,371.0,26.0,4.0,26.0
9dc1a7de274444849c219cff195d0b71,housewares,625.0,20.0,17.0,13.0
...,...,...,...,...,...
a0b7d5a992ccda646f2d34e418fff5a0,furniture_decor,12300.0,40.0,40.0,40.0
bf4538d88321d0fd4412a93c974510e6,construction_tools_lights,1700.0,16.0,19.0,16.0
9a7c6041fa9592d9d9ef6cfe62a71f8c,bed_bath_table,1400.0,27.0,7.0,27.0
83808703fc0706a22e264b9d75f04a2e,computers_accessories,700.0,31.0,13.0,20.0
106392145fca363410d287a815be6de4,bed_bath_table,2083.0,12.0,2.0,7.0

In [33]:
df_merged.to_csv('./dbt_ecomm/seeds/clean_olist_products.csv', index=True)